Signor 3.0

In [3]:
targetGene = 'GBA'

In [3]:
import pandas as pd
final_df = pd.DataFrame(columns=['Database','TF','TargetGene','Library/PMID'])

In [ ]:
import http.client
import pandas as pd
from io import StringIO

# ids of Fatty Acid Biosynthesis

ids = ['O14757']

final_df = pd.DataFrame(columns=['Database','TF','TargetGene','Library/PMID'])

for uid in ids:

    # Establish connection
    conn = http.client.HTTPSConnection("signor.uniroma2.it")

    # Define headers
    headersList = {
        "Accept": "*/*",
        "User-Agent": "Thunder Client (https://www.thunderclient.com)"
    }

    # Empty payload
    payload = ""

    # Make the request
    conn.request("GET", f"/getData.php?id={uid}&organism=9606", payload, headersList)

    # Get the response
    response = conn.getresponse()
    result = response.read()

    # Decode the response as a string
    decoded_result = result.decode("utf-8")

    # Convert the string data into a pandas DataFrame
    data = StringIO(decoded_result)
    df1 = pd.read_csv(data, sep='\t',header = None)

    if(len(df1) <= 1):
        continue

    print(df1)

    mask = (df1[9] == 'transcriptional regulation')

    for i in range(0,len(df1[mask])):
        new_row = {'Database' : 'Signor', 'TF' : list(df1[mask][0])[i],'TargetGene':list(df1[mask][4])[i],'Library/PMID':list(df1[mask][21])[0]}
        final_df = pd.concat([final_df, pd.DataFrame([new_row])],ignore_index = True)

                                                   0         1             2   \
0                                               CHEK1   protein        O14757
1                                               CHEK1   protein        O14757
2                                               CHEK1   protein        O14757
3   3-(carbamoylamino)-5-(3-fluorophenyl)-N-[(3S)-...  chemical  CHEBI:131156
4                                               CHEK1   protein        O14757
..                                                ...       ...           ...
79                                              CHEK1   protein        O14757
80                                               CDK1   protein        P06493
81                                               CDK2   protein        P24941
82                                              CHEK1   protein        O14757
83                                              CHEK1   protein        O14757

         3      4        5       6        7   \
0   UNIPROT  RAD51  protein  Q06609  UNIPROT
1   UNIPROT  FANCE  protein  Q9HB96  UNIPROT
2   UNIPROT    BLM  protein  P54132  UNIPROT
3     ChEBI  CHEK1  protein  O14757  UNIPROT
4   UNIPROT  CHEK1  protein  O14757  UNIPROT
..      ...    ...      ...     ...      ...
79  UNIPROT   TLK2  protein  Q86UE8  UNIPROT
80  UNIPROT  CHEK1  protein  O14757  UNIPROT
81  UNIPROT  CHEK1  protein  O14757  UNIPROT
82  UNIPROT   TP53  protein  P04637  UNIPROT
83  UNIPROT    RB1  protein  P06400  UNIPROT

                                            8                    9   ...  19  \
0                                 up-regulates      phosphorylation  ... NaN
1                                 up-regulates      phosphorylation  ... NaN
2   down-regulates quantity by destabilization      phosphorylation  ... NaN
3                               down-regulates  chemical inhibition  ... NaN
4                        up-regulates activity      phosphorylation  ... NaN
..                                         ...                  ...  ...  ..
79                     down-regulates activity      phosphorylation  ... NaN
80                                up-regulates      phosphorylation  ... NaN
81                                up-regulates      phosphorylation  ... NaN
82                       up-regulates activity      phosphorylation  ... NaN
83                       up-regulates activity      phosphorylation  ... NaN

    20        21 22       23         24  \
0  NaN  15665856  t      NaN  gcesareni
1  NaN  17296736  t      NaN    llicata
2  NaN  26028025  t      NaN     miannu
3  NaN     Other  t  Selleck  gcesareni
4  NaN  23068608  t      NaN  lperfetto
..  ..       ... ..      ...        ...
79 NaN  12955071  t      NaN     miannu
80 NaN  21765472  t      NaN  lperfetto
81 NaN  21765472  t      NaN  lperfetto
82 NaN  15659650  t      NaN  lperfetto
83 NaN  17380128  t      NaN    llicata

                                                   25             26     27  \
0   We demonstrate that chk1 interacts with rad51,...  SIGNOR-133375  0.836
1   Chk1 directly phosphorylates the fance subunit...  SIGNOR-153027  0.705
2   We now provide evidence that BLM undergoes K48...  SIGNOR-276909  0.772
3                                                 NaN  SIGNOR-190203  0.800
4   TheSer296autophosphorylation ofCHK1is mainly r...  SIGNOR-217904  0.200
..                                                ...            ...    ...
79  Chk1 phosphorylates GST-fusion fragments of TL...  SIGNOR-262740  0.273
80  Chk1 itself is also subject to cdk-mediated ph...  SIGNOR-175071  0.419
81  Chk1 itself is also subject to cdk-mediated ph...  SIGNOR-175079  0.534
82  CHK1 and CHK2 phosphorylate the p53 N terminus...  SIGNOR-217799  0.772
83  These results suggest that ser612 is phosphory...  SIGNOR-153904  0.432

    28
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN
..  ..
79 NaN
80 NaN
81 NaN
82 NaN
83 NaN

[84 rows x 29 columns]

In [2]:
final_df

  Database      TF TargetGene Library/PMID
0   Signor  MEK1/2      CHEK1     28138032


ChEA3

In [1]:
#### It returns all the TFs and a mapping to which query gene they belong to under the attribute Overlapping_Gene####

import requests
import json

# List of genes
targetGene = 'PLA2G2A'
genes = [targetGene,"SCD"]

# URL of the ChEA3 API endpoint
url = "https://maayanlab.cloud/chea3/api/enrich/"

# Payload to send with the POST request
payload = {
    "query_name": "myQuery",
    "gene_set": genes
}

# POST to ChEA3 server
response = requests.post(url, json=payload)

# Check if the request was successful
if response.status_code == 200:
    # Parse the JSON response
    results = response.json()
    # print(results)
    # If you want to pretty-print the results
    # print(json.dumps(results, indent=2))
else:
    print(f"Request failed with status code {response.status_code}")


# allTFs = response['Integrated--meanRank']

In [2]:
print(results.keys())

dict_keys(['Integrated--meanRank', 'Integrated--topRank', 'GTEx--Coexpression', 'ReMap--ChIP-seq', 'Enrichr--Queries', 'ENCODE--ChIP-seq', 'ARCHS4--Coexpression', 'Literature--ChIP-seq'])

In [9]:
temp = results['Literature--ChIP-seq']
# temp = results['Enrichr--Queries']
modified = []
for res in temp:
    overlap = res.get('Overlapping_Genes','notfound')
    if overlap != '' and overlap != 'notfound':
        modified.append(res)

In [10]:
modified

[{'Query Name': 'myQuery',
  'Rank': '1',
  'Scaled Rank': '0.006098',
  'Set_name': 'HIF1A_21447827_CHIPSEQ_MCF7_HUMAN',
  'TF': 'HIF1A',
  'Intersect': '1',
  'Set length': '292',
  'FET p-value': '0.04255',
  'FDR': '1.0',
  'Odds Ratio': '34.36',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'SCD'},
 {'Query Name': 'myQuery',
  'Rank': '2',
  'Scaled Rank': '0.0122',
  'Set_name': 'NR1H3_23393188_CHIPSEQ_ATHEROSCLEROTICFOAM_HUMAN',
  'TF': 'NR1H3',
  'Intersect': '1',
  'Set length': '577',
  'FET p-value': '0.08179',
  'FDR': '1.0',
  'Odds Ratio': '17.36',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'SCD'},
 {'Query Name': 'myQuery',
  'Rank': '3',
  'Scaled Rank': '0.01829',
  'Set_name': 'NR3C1_23031785_CHIPSEQ_PC12_MOUSE',
  'TF': 'NR3C1',
  'Intersect': '1',
  'Set length': '793',
  'FET p-value': '0.1101',
  'FDR': '1.0',
  'Odds Ratio': '12.63',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'SCD'},
 {'Query Name': 'myQuery',
  'Rank': '4',
  'Scaled Rank': '0.02439',
  'Set_name': 'EOMES_21245162_CHIPSEQ_HESC_HUMAN',
  'TF': 'EOMES',
  'Intersect': '1',
  'Set length': '880',
  'FET p-value': '0.1212',
  'FDR': '1.0',
  'Odds Ratio': '11.38',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'SCD'},
 {'Query Name': 'myQuery',
  'Rank': '5',
  'Scaled Rank': '0.03049',
  'Set_name': 'SOX11_23321250_CHIPCHIP_Z138A519JVM2_HUMAN',
  'TF': 'SOX11',
  'Intersect': '1',
  'Set length': '970',
  'FET p-value': '0.1325',
  'FDR': '1.0',
  'Odds Ratio': '10.32',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'SCD'},
 {'Query Name': 'myQuery',
  'Rank': '6',
  'Scaled Rank': '0.03659',
  'Set_name': 'HNF4A_19761587_CHIPCHIP_CACO2_HUMAN',
  'TF': 'HNF4A',
  'Intersect': '1',
  'Set length': '1033',
  'FET p-value': '0.1402',
  'FDR': '1.0',
  'Odds Ratio': '9.689',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'SCD'},
 {'Query Name': 'myQuery',
  'Rank': '7',
  'Scaled Rank': '0.04268',
  'Set_name': 'SPI1_20176806_CHIPSEQ_THIOMACROPHAGE_MOUSE',
  'TF': 'SPI1',
  'Intersect': '1',
  'Set length': '1341',
  'FET p-value': '0.1769',
  'FDR': '1.0',
  'Odds Ratio': '7.462',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'PLA2G2A'},
 {'Query Name': 'myQuery',
  'Rank': '8',
  'Scaled Rank': '0.04878',
  'Set_name': 'POU5F1_18347094_CHIPCHIP_MESC_MOUSE',
  'TF': 'POU5F1',
  'Intersect': '1',
  'Set length': '1748',
  'FET p-value': '0.2223',
  'FDR': '1.0',
  'Odds Ratio': '5.724',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'PLA2G2A'},
 {'Query Name': 'myQuery',
  'Rank': '9',
  'Scaled Rank': '0.05488',
  'Set_name': 'SMAD3_18955504_CHIPCHIP_HACAT_HUMAN',
  'TF': 'SMAD3',
  'Intersect': '1',
  'Set length': '1759',
  'FET p-value': '0.2235',
  'FDR': '1.0',
  'Odds Ratio': '5.688',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'SCD'},
 {'Query Name': 'myQuery',
  'Rank': '10',
  'Scaled Rank': '0.06098',
  'Set_name': 'TCF3_18347094_CHIPCHIP_MESC_MOUSE',
  'TF': 'TCF3',
  'Intersect': '1',
  'Set length': '1838',
  'FET p-value': '0.2318',
  'FDR': '1.0',
  'Odds Ratio': '5.443',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'PLA2G2A'},
 {'Query Name': 'myQuery',
  'Rank': '11',
  'Scaled Rank': '0.06707',
  'Set_name': 'FOXA1_25552417_CHIPSEQ_VCAP_HUMAN',
  'TF': 'FOXA1',
  'Intersect': '1',
  'Set length': '1842',
  'FET p-value': '0.2323',
  'FDR': '1.0',
  'Odds Ratio': '5.431',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'PLA2G2A'},
 {'Query Name': 'myQuery',
  'Rank': '12',
  'Scaled Rank': '0.07317',
  'Set_name': 'GATA3_24758297_CHIPSEQ_MCF7_HUMAN',
  'TF': 'GATA3',
  'Intersect': '1',
  'Set length': '1844',
  'FET p-value': '0.2325',
  'FDR': '1.0',
  'Odds Ratio': '5.425',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'PLA2G2A'},
 {'Query Name': 'myQuery',
  'Rank': '13',
  'Scaled Rank': '0.07927',
  'Set_name': 'GATA4_25053715_CHIPSEQ_YYC3_HUMAN',
  'TF': 'GATA4',
  'Intersect': '1',
  'Set length': '1845',
  'FET p-value': '0.2326',
  'FDR': '1.0',
  'Odds Ratio': '5.422',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'PLA2G2A'},
 {'Query Name': 'myQuery',
  'Rank': '14',
  'Scaled Rank': '0.08537',
  'Set_name': 'HOXC9_25013753_CHIPSEQ_NEUROBLASTOMABE2C_HUMAN',
  'TF': 'HOXC9',
  'Intersect': '1',
  'Set length': '1851',
  'FET p-value': '0.2332',
  'FDR': '1.0',
  'Odds Ratio': '5.405',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'SCD'},
 {'Query Name': 'myQuery',
  'Rank': '15',
  'Scaled Rank': '0.09146',
  'Set_name': 'GATA6_25053715_CHIPSEQ_YYC3_HUMAN',
  'TF': 'GATA6',
  'Intersect': '1',
  'Set length': '1852',
  'FET p-value': '0.2333',
  'FDR': '1.0',
  'Odds Ratio': '5.402',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'PLA2G2A'},
 {'Query Name': 'myQuery',
  'Rank': '16',
  'Scaled Rank': '0.09756',
  'Set_name': 'GATA2_19941826_CHIPSEQ_K562_HUMAN',
  'TF': 'GATA2',
  'Intersect': '1',
  'Set length': '1921',
  'FET p-value': '0.2405',
  'FDR': '1.0',
  'Odds Ratio': '5.208',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'SCD'},
 {'Query Name': 'myQuery',
  'Rank': '17',
  'Scaled Rank': '0.1037',
  'Set_name': 'GATA1_21571218_CHIPSEQ_MEGAKARYOCYTES_HUMAN',
  'TF': 'GATA1',
  'Intersect': '1',
  'Set length': '2390',
  'FET p-value': '0.2873',
  'FDR': '1.0',
  'Odds Ratio': '4.185',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'SCD'},
 {'Query Name': 'myQuery',
  'Rank': '18',
  'Scaled Rank': '0.1098',
  'Set_name': 'FOXA2_19822575_CHIPSEQ_HEPG2_HUMAN',
  'TF': 'FOXA2',
  'Intersect': '1',
  'Set length': '2814',
  'FET p-value': '0.3263',
  'FDR': '1.0',
  'Odds Ratio': '3.555',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'PLA2G2A'},
 {'Query Name': 'myQuery',
  'Rank': '19',
  'Scaled Rank': '0.1159',
  'Set_name': 'RUNX1_21571218_CHIPSEQ_MEGAKARYOCYTES_HUMAN',
  'TF': 'RUNX1',
  'Intersect': '1',
  'Set length': '4661',
  'FET p-value': '0.4666',
  'FDR': '1.0',
  'Odds Ratio': '2.146',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'SCD'},
 {'Query Name': 'myQuery',
  'Rank': '20',
  'Scaled Rank': '0.122',
  'Set_name': 'MITF_21258399_CHIPSEQ_MELANOMA_HUMAN',
  'TF': 'MITF',
  'Intersect': '1',
  'Set length': '5140',
  'FET p-value': '0.4965',
  'FDR': '1.0',
  'Odds Ratio': '1.946',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'SCD'},
 {'Query Name': 'myQuery',
  'Rank': '21',
  'Scaled Rank': '0.128',
  'Set_name': 'EGR1_20690147_CHIPSEQ_ERYTHROLEUKEMIA_HUMAN',
  'TF': 'EGR1',
  'Intersect': '1',
  'Set length': '5768',
  'FET p-value': '0.5324',
  'FDR': '1.0',
  'Odds Ratio': '1.734',
  'Library': 'Literature--ChIP-seq',
  'Overlapping_Genes': 'SCD'}]

In [19]:
allTFs = results['Literature--ChIP-seq']
# print(json.dumps(allTFs,indent=2))

for dump in allTFs:
    pmid = dump['Set_name'].split('_')[1]
    human = dump['Set_name'].split('_')[-1]
    if human == "HUMAN":
        overLappingGenes = dump['Overlapping_Genes'].split(',')
        if(targetGene in overLappingGenes):
            new_row = {'Database' : 'CHEA', 'TF' : dump["TF"],'TargetGene':targetGene,'Library/PMID':pmid}
            final_df = pd.concat([final_df, pd.DataFrame([new_row])],ignore_index = True)

In [20]:
final_df

   Database      TF TargetGene Library/PMID
0      CHEA      AR     PLA2G5     25329375
1      CHEA   TCF21     PLA2G5     26020271
2      CHEA     MYC     PLA2G5     19915707
3      CHEA    PBX1     PLA2G5     22567123
4      CHEA   STAT3     PLA2G5     23295773
5      CHEA    TP63    PLA2G4B     22573176
6      CHEA    MYCN      CHEK1     21190229
7      CHEA   STAT1      CHEK1     20625510
8      CHEA    E2F4      CHEK1     17652178
9      CHEA    E2F1      CHEK1     21310950
10     CHEA   BACH1      CHEK1     22875853
11     CHEA  POU3F2      CHEK1     20337985
12     CHEA    EGR1      CHEK1     20690147
13     CHEA   FOXA1      CHEK1     25329375
14     CHEA    ELK3      CHEK1     25401928
15     CHEA    CUX1      CHEK1     19635798
16     CHEA   PPARD      CHEK1     21283829
17     CHEA    RBPJ    PLA2G4D     21746931
18     CHEA   GATA3    PLA2G4D     24758297
19     CHEA    ELK3    PLA2G4D     25401928
20     CHEA    TP63    PLA2G4D     23658742
21     CHEA   FOXA1    PLA2G2A     25552417
22     CHEA   GATA3    PLA2G2A     24758297
23     CHEA   GATA4    PLA2G2A     25053715
24     CHEA   GATA6    PLA2G2A     25053715
25     CHEA   FOXA2    PLA2G2A     19822575

In [21]:
final_df.to_csv('D:/Raylab/LiMeNEx/FetchData/temp1.csv')

trrust

In [19]:
import pandas as pd

df2 = pd.read_csv('D:\\Raylab\\LiMeNEx\\FetchData\\trrust_rawdata.human.tsv',sep = '\t' ,header= None)
df2.columns = ['TF','Target','Regulation','PMID']

df2.head()

df2 = df2[(df2["Target"] == targetGene)]

for i in range(0,len(df2)):
    new_row = {'Database' : 'TRRUST', 'TF' : list(df2['TF'])[i],'TargetGene':targetGene,'Library/PMID':list(df2["PMID"])[i]}
    final_df = pd.concat([final_df, pd.DataFrame([new_row])],ignore_index = True)

In [20]:
final_df

   Database       TF TargetGene          Library/PMID
0    Signor    PPARD   SLC25A20              19577614
1    Signor    PPARA   SLC25A20              19577614
2      CHEA    HNF4A   SLC25A20  Literature--ChIP-seq
3      CHEA      VDR   SLC25A20  Literature--ChIP-seq
4      CHEA     CDX2   SLC25A20  Literature--ChIP-seq
5      CHEA    PPARD   SLC25A20  Literature--ChIP-seq
6      CHEA    NANOG   SLC25A20  Literature--ChIP-seq
7      CHEA      ERG   SLC25A20  Literature--ChIP-seq
8      CHEA     TCF3   SLC25A20  Literature--ChIP-seq
9      CHEA      SRF   SLC25A20  Literature--ChIP-seq
10     CHEA    ZFP42   SLC25A20  Literature--ChIP-seq
11     CHEA     RARB   SLC25A20  Literature--ChIP-seq
12     CHEA     RARA   SLC25A20  Literature--ChIP-seq
13     CHEA  NEUROD2   SLC25A20  Literature--ChIP-seq
14     CHEA     FLI1   SLC25A20  Literature--ChIP-seq
15     CHEA    OLIG2   SLC25A20  Literature--ChIP-seq
16     CHEA    FOXO3   SLC25A20  Literature--ChIP-seq
17     CHEA    FOXA1   SLC25A20  Literature--ChIP-seq
18     CHEA       AR   SLC25A20  Literature--ChIP-seq
19     CHEA     SPI1   SLC25A20  Literature--ChIP-seq
20     CHEA     SOX2   SLC25A20  Literature--ChIP-seq
21     CHEA    STAT3   SLC25A20  Literature--ChIP-seq
22     CHEA    PPARG   SLC25A20  Literature--ChIP-seq
23     CHEA   POU5F1   SLC25A20  Literature--ChIP-seq
24   TRRUST    PPARA   SLC25A20              19748481
25   TRRUST      SP1   SLC25A20              21130740

Save CSV file

In [98]:
final_df.to_csv(f"D:/Raylab/LiMeNEx/FetchData/{targetGene}.csv")